export const TYPES = {
  FETCHING_CONTACTS: "FETCHING_CONTACTS",
  FETCHING_CONTACTS_SUCCESS: "FETCHING_CONTACTS_SUCCESS",
  FETCHING_CONTACTS_FAILURE: "FETCHING_CONTACTS_FAILURE",

  SET_CURRENT_CONTACT: "SET_CURRENT_CONTACT"
};
