export const TYPES = {
  FETCHING_CONTACTS: "FETCHING_CONTACTS",
  FETCHING_CONTACTS_SUCCESS: "FETCHING_CONTACTS_SUCCESS",
  FETCHING_CONTACTS_FAILURE: "FETCHING_CONTACTS_FAILURE",

  SET_CURRENT_CONTACT: "SET_CURRENT_CONTACT",

  SEND_CONTACT: "SEND_CONTACT",
  SEND_CONTACT_SUCCESS: "SEND_CONTACT_SUCCESS",
  SEND_CONTACT_FAILURE: "SEND_CONTACT_FAILURE",

  EDIT_CONTACT: "EDIT_CONTACT",
  EDIT_CONTACT_SUCCESS: "EDIT_CONTACT_SUCCESS",
  EDIT_CONTACT_FAILURE: "EDIT_CONTACT_FAILURE"
};
